# Site settings
title: Yuanyu Blog
SEOTitle: 渊鱼 | BY Blog
header-img: img/post-bg-desk.jpg
email: mhyhym@163.com
description: "once up on there was a writer"
keyword: "琐记, 脑洞, 坑"
url: "http://lieainwater.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog

# Sidebar settings
sidebar: not                      # whether or not using Sidebar.
sidebar-about-description: "鱼潜在渊，或在于渚"
sidebar-avatar:      # use absolute URL, seeing it's used in both `/` and `/about/


# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: lieainwater



# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 5          # 相同标签数量大于这个数，才会出现在首页


